<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-UB1VBSH" failures="1" tests="2" name="Test" time="375.245" errors="0" timestamp="2025-02-04T17:53:48 IST">
  <testcase classname="Revenue_Income_Certificate_Service.Income_01" name="income_Certificate_Process" time="153.253"/>
  <testcase classname="Revenue_Income_Certificate_Service.Income_Dept_01" name="validate_income_dept" time="170.618">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at base_test.BaseClass.endReport(BaseClass.java:266)
at Revenue_Income_Certificate_Service.Income_Dept_01.validate_income_dept(Income_Dept_01.java:524)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validate_income_dept -->
  <testcase classname="base_test.BaseClass" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="base_test.BaseClass" name="@AfterSuite configAfterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite configAfterSuite -->
  <testcase classname="base_test.BaseClass" name="@BeforeSuite configBeforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite configBeforeSuite -->
  <testcase classname="base_test.BaseClass" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
</testsuite> <!-- Test -->
